"""
Generate Psycode behavior image set pkl from raw originals.

Reprocesses all 8 images through the standard Allen Visual Coding
luminance-matching pipeline, exactly replicating the procedure from
2019_05_29_create_E_F_reproc_set-Copy1.ipynb.

Pipeline order:
  1. Load raw image (BSDS .jpg, VHC .imc, McGill .tif)
  2. Apply gamma decoding (power 2.2 for BSDS/McGill, no-op for VHC)
  3. Crop to 16:10 aspect ratio + resize to prewarp size (918 x 1174)
     (replicates scipy.misc.imresize bytescale + PIL BILINEAR)
  4. Compute target_luminance = uint8(255 * median(mean_to_max_ratio))
  5. fit_scale_to_saturation(target_luminance, target_saturation=2,
                             apply_screen_mask=True)
  6. convert_8bit  (clip [0,255] and cast to uint8)
  7. crop_prewarp_img  (set pixels outside screen mask to 127)

Image indices from Allen Visual Coding 118 natural scenes:
  [18, 0, 25, 70, 39, 117, 88, 38]

Raw original sources (matched via correlation):
  im000 -> 100075.jpg           (BSDS Test,  corr=0.929)
  im018 -> 135037.jpg           (BSDS Test,  corr=0.920)
  im025 -> 173036.jpg           (BSDS Test,  corr=0.953)
  im038 -> 309004.jpg           (BSDS Test,  corr=0.861)
  im039 -> 326038.jpg           (BSDS Test,  corr=0.902)
  im070 -> imk01251.imc         (VHC temp,   corr=0.987)
  im088 -> imk01733.imc         (VHC temp,   corr=0.929)
  im117 -> pippin_Mex07_030.tif (McGill,     corr=0.888)

Author: Generated by Copilot, 2025
"""

import os
import sys
import glob
import array
import pickle
import numpy as np
from PIL import Image
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# For Allen Brain Observatory screen mask
import allensdk.brain_observatory.stimulus_info as si


# ============================================================================
# Configuration
# ============================================================================

WORKING_DIR = (
    r'Z:\braintv\workgroups\ophysdev\OPhysCore'
    r'\Data driven decision - Do not DELETE'
    r'\2019-05-28 - Create new image set CD'
)

VHC_TEMP_DIR = (
    r'\\allen\programs\braintv\workgroups\cortexmodels\michaelbu'
    r'\mat_backup\michaelbu\Natural_Image_Processing'
    r'\Original_Images\vhc_temp'
)

# Each entry: pkl_name, raw filename, database source
# For BSDS/McGill files are found via glob under Original_Images/
# For VHC files come from the curated vhc_temp network folder
IMAGE_SPECS = [
    {'pkl_name': 'im000', 'filename': '100075.jpg',            'source': 'BSDS'},
    {'pkl_name': 'im018', 'filename': '135037.jpg',            'source': 'BSDS'},
    {'pkl_name': 'im025', 'filename': '173036.jpg',            'source': 'BSDS'},
    {'pkl_name': 'im038', 'filename': '309004.jpg',            'source': 'BSDS'},
    {'pkl_name': 'im039', 'filename': '326038.jpg',            'source': 'BSDS'},
    {'pkl_name': 'im070', 'filename': 'imk01251.imc',          'source': 'VHC'},
    {'pkl_name': 'im088', 'filename': 'imk01733.imc',          'source': 'VHC'},
    {'pkl_name': 'im117', 'filename': 'pippin_Mex07_030.tif',  'source': 'McGill'},
]

OUTPUT_PKL = os.path.join(
    WORKING_DIR, 'Psycode imaging set',
    'Natural_Images_Lum_Matched_set_Psycode_2026.04.08.pkl'
)
OUTPUT_PREVIEW = os.path.join(
    WORKING_DIR, 'Psycode imaging set',
    'Psycode_set_reprocessed_preview.png'
)


# ============================================================================
# Self-contained pipeline functions
# (inlined to avoid broken import chain from deprecated scipy.misc.imresize)
# ============================================================================

# ---------- Image loading ----------

def read_from_img_file(path_file):
    """Load BSDS (.jpg) or McGill (.tif) as grayscale numpy array (uint8)."""
    img = Image.open(path_file)
    img = img.convert('L')
    return np.array(img)


def read_from_imc_raw_files(path_file):
    """Load VHC .imc binary file as uint16 numpy array (1024 x 1536).
    Original code provided by Michael Buice."""
    with open(path_file, 'rb') as im:
        s = im.read()
    arr = array.array('H', s)
    arr.byteswap()
    return np.array(arr, dtype='uint16').reshape(1024, 1536)


def load_img(path_file, database_source):
    """Load raw image based on database source."""
    if database_source in ('BSDS', 'McGill'):
        return read_from_img_file(path_file)
    elif database_source == 'VHC':
        return read_from_imc_raw_files(path_file)
    else:
        raise ValueError(f"Unknown database source: {database_source}")


# ---------- Gamma decoding ----------

def apply_gamma_decoding(img, database_source):
    """Apply gamma decoding: power 2.2 for BSDS/McGill, no-op for VHC."""
    if database_source in ('BSDS', 'McGill'):
        img = np.power(img.astype('float64'), 2.2)
    return img


# ---------- imresize replacement ----------

def _bytescale(data):
    """Replicate scipy.misc.bytescale: map [min, max] -> [0, 255] uint8."""
    cmin = float(data.min())
    cmax = float(data.max())
    cscale = cmax - cmin
    if cscale == 0:
        cscale = 1.0
    scale = 255.0 / cscale
    bytedata = (data.astype('float64') - cmin) * scale
    return (bytedata.clip(0, 255) + 0.5).astype(np.uint8)


def _imresize(arr, size):
    """Replicate scipy.misc.imresize(arr, size, interp='bilinear').

    Parameters
    ----------
    arr : ndarray
        Input image. If not uint8, bytescale is applied first
        (maps [min, max] to [0, 255]), matching original scipy behavior.
    size : tuple (height, width)
        Target size in numpy (row, col) convention.

    Returns
    -------
    ndarray uint8
        Resized image.
    """
    if arr.dtype != np.uint8:
        arr = _bytescale(arr)
    im = Image.fromarray(arr, mode='L')
    # PIL resize expects (width, height)
    im = im.resize((size[1], size[0]), Image.BILINEAR)
    return np.array(im)


# ---------- Cropping / resizing ----------

def crop_raw_images(data):
    """Crop to 16:10 aspect ratio and resize to prewarp size (918 x 1174).

    Replicates process_images.crop_raw_images exactly, replacing the
    deprecated scipy.misc.imresize with _imresize.
    """
    monitor_size = (1920, 1200)   # (width, height)
    warp_size = (1174, 918)       # (width, height)

    crop_x = int((monitor_size[0] - warp_size[0]) / 2)   # 373
    crop_y = int((monitor_size[1] - warp_size[1]) / 2)   # 141

    h, w = data.shape

    # Force 16:10 aspect ratio
    ratio_comparison = 10 * w - 16 * h
    if ratio_comparison > 0:
        excess = ratio_comparison / 10.0
        x = int(excess / 2.0)
        data = data[:, x:(w - x)]
    elif ratio_comparison < 0:
        excess = -ratio_comparison / 16.0
        x = int(excess / 2.0)
        data = data[x:(h - x), :]

    # Resize to full monitor size, then crop to warp area
    data = _imresize(data, size=(monitor_size[1], monitor_size[0]))
    data = data[crop_y:(monitor_size[1] - crop_y),
                crop_x:(monitor_size[0] - crop_x)]

    return data


# ---------- 8-bit conversion ----------

def convert_8bit(data):
    """Clip to [0, 255] and cast to uint8."""
    data[data >= 255] = 255
    data[data <= 0] = 0
    data = data.astype('uint8')
    return data


# ---------- Screen mask ----------

def get_screen_mask():
    """Allen Brain Observatory screen mask, cropped to prewarp size."""
    monitor_size = (1920, 1200)
    warp_size = (1174, 918)

    crop_x = int((monitor_size[0] - warp_size[0]) / 2)
    crop_y = int((monitor_size[1] - warp_size[1]) / 2)

    mask_screen = si.make_display_mask(display_shape=(1200, 1920))
    mask_screen = mask_screen[crop_y:(monitor_size[1] - crop_y),
                              crop_x:(monitor_size[0] - crop_x)]
    return mask_screen


def crop_prewarp_img(data, set_value=127):
    """Apply screen mask: set pixels outside the screen area to set_value."""
    mask_screen = get_screen_mask()
    data[mask_screen == 0] = set_value
    return data


# ---------- Saturation / luminance matching ----------

def get_percent_under_and_oversaturated_8bit(img):
    """Percentage of pixels that would be clipped at 0 or 255."""
    img = convert_8bit(img.copy())
    nb_sat = float(len(np.where(img == 255)[0]))
    nb_under_sat = float(len(np.where(img == 0)[0]))
    total_pix = len(img.flatten())
    return 100.0 * (nb_sat + nb_under_sat) / total_pix


def fit_scale_to_saturation(data, target_luminance=127,
                            target_saturation=2, apply_screen_mask=True):
    """Scale image so mean -> target_luminance, with at most
    target_saturation % of pixels clipped.

    Replicates process_images.fit_scale_to_saturation exactly.
    """
    local_img = data.astype('float64')

    if apply_screen_mask:
        mask_screen = get_screen_mask()
        list_pixel = local_img[mask_screen != 0].flatten()
    else:
        list_pixel = local_img.flatten()

    mean_img = np.mean(list_pixel)
    list_pixel = list_pixel - mean_img

    list_value_sorted = np.sort(np.unique(np.abs(list_pixel)))
    percent_sat = 0
    index = -1

    while percent_sat < target_saturation:
        scaling = float(target_luminance) / list_value_sorted[index]
        local_img_tmp = list_pixel * scaling + float(target_luminance)
        percent_sat = get_percent_under_and_oversaturated_8bit(local_img_tmp)
        index = index - 1

    if index == -2:
        index = -1
    else:
        index = index + 2

    scaling = float(target_luminance) / list_value_sorted[index]
    local_img = (local_img - mean_img) * scaling + float(target_luminance)

    return local_img


# ---------- Validation ----------

def get_mean_to_max_ratio(img, percentile=1):
    """Compute (mean - p_low) / (p_high - p_low) ratio."""
    mean_img = np.mean(img.flatten())
    max_img = np.percentile(img.flatten(), 100 - percentile)
    min_img = np.percentile(img.flatten(), percentile)
    return (mean_img - min_img) / (max_img - min_img)


# ============================================================================
# Resolve file paths
# ============================================================================

def resolve_paths(specs, working_dir, vhc_dir):
    """Find the full path for each image, using glob for BSDS/McGill."""
    for spec in specs:
        if spec['source'] == 'VHC':
            spec['path'] = os.path.join(vhc_dir, spec['filename'])
        else:
            # Search recursively under Original_Images/
            pattern = os.path.join(working_dir, 'Original_Images',
                                   '**', spec['filename'])
            matches = glob.glob(pattern, recursive=True)
            if len(matches) == 0:
                raise FileNotFoundError(
                    f"Could not find {spec['filename']} under Original_Images/")
            spec['path'] = matches[0]
    return specs


# ============================================================================
# Main
# ============================================================================

def main():
    os.chdir(WORKING_DIR)

    # --- Resolve all file paths ---
    print("Resolving source file paths...")
    resolve_paths(IMAGE_SPECS, WORKING_DIR, VHC_TEMP_DIR)

    print("\nVerifying source files exist:")
    all_ok = True
    for spec in IMAGE_SPECS:
        exists = os.path.isfile(spec['path'])
        tag = "OK" if exists else "MISSING"
        print(f"  {spec['pkl_name']}  {spec['source']:7s}  "
              f"{os.path.basename(spec['path'])}  [{tag}]")
        if not exists:
            all_ok = False
    if not all_ok:
        print("\nERROR: Some source files are missing. Aborting.")
        sys.exit(1)

    # ===== PASS 1: Load -> gamma decode -> crop -> compute target luminance =
    print("\n========== Pass 1: Computing target luminance ==========")
    cropped_images = {}
    all_ratios = []

    for spec in IMAGE_SPECS:
        name = spec['pkl_name']
        print(f"\n  [{name}]  {spec['source']}: {spec['filename']}")

        # 1. Load raw
        raw = load_img(spec['path'], spec['source'])
        print(f"    Raw shape: {raw.shape}  dtype: {raw.dtype}")

        # 2. Gamma decode (power 2.2 for BSDS/McGill, no-op for VHC)
        decoded = apply_gamma_decoding(raw, spec['source'])

        # 3. Crop edges + resize to prewarp size (918 x 1174)
        cropped = crop_raw_images(decoded)
        print(f"    Cropped shape: {cropped.shape}  dtype: {cropped.dtype}")

        cropped_images[name] = cropped

        # 4. Mean-to-max ratio
        ratio = get_mean_to_max_ratio(cropped)
        all_ratios.append(ratio)
        print(f"    Mean-to-max ratio: {ratio:.4f}")

    mean_ratio = np.median(all_ratios)
    target_luminance = np.uint8(255.0 * mean_ratio)
    print(f"\n  Median ratio across 8 images: {mean_ratio:.4f}")
    print(f"  >>> target_luminance = {target_luminance}")

    # ===== PASS 2: Luminance match -> 8-bit -> screen mask -> save =========
    print("\n========== Pass 2: Luminance matching & saving ==========")
    dict_image = {}

    for spec in IMAGE_SPECS:
        name = spec['pkl_name']
        print(f"\n  [{name}]")

        local_img = cropped_images[name].astype('float64')

        # 5. Fit scale to saturation
        local_img = fit_scale_to_saturation(
            local_img,
            target_luminance=target_luminance,
            target_saturation=2,
            apply_screen_mask=True,
        )

        # 6. Convert to uint8
        local_img = convert_8bit(local_img)

        # 7. Apply screen mask (outside -> 127)
        local_img = crop_prewarp_img(local_img)

        dict_image[name] = {}
        dict_image[name][name] = local_img

        print(f"    shape: {local_img.shape}  dtype: {local_img.dtype}  "
              f"range: [{local_img.min()}, {local_img.max()}]  "
              f"mean: {local_img.mean():.1f}")

    # --- Save pkl ---
    os.makedirs(os.path.dirname(OUTPUT_PKL), exist_ok=True)
    with open(OUTPUT_PKL, 'wb') as handle:
        pickle.dump(dict_image, handle, protocol=pickle.HIGHEST_PROTOCOL)
    print(f"\nSaved pkl -> {OUTPUT_PKL}")

    # --- Verify pkl ---
    print("\nVerifying saved pkl...")
    with open(OUTPUT_PKL, 'rb') as f:
        loaded = pickle.load(f)
    print(f"  Keys: {sorted(loaded.keys())}")
    for k in sorted(loaded.keys()):
        arr = loaded[k][k]
        print(f"  {k}: shape={arr.shape}  dtype={arr.dtype}  "
              f"range=[{arr.min()}, {arr.max()}]  mean={arr.mean():.1f}")

    # --- Create tiled preview ---
    print("\nCreating preview image...")
    fig, axes = plt.subplots(2, 4, figsize=(20, 10))
    sorted_names = sorted(dict_image.keys())
    for idx, name in enumerate(sorted_names):
        row, col = idx // 4, idx % 4
        ax = axes[row, col]
        ax.imshow(dict_image[name][name], cmap='gray', vmin=0, vmax=255)
        ax.set_title(name, fontsize=14)
        ax.axis('off')
    plt.suptitle(
        f'Psycode Set - Reprocessed from Raw Originals  '
        f'(target_luminance={target_luminance})',
        fontsize=16,
    )
    plt.tight_layout()
    plt.savefig(OUTPUT_PREVIEW, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Saved preview -> {OUTPUT_PREVIEW}")

    print("\n========== Done! ==========")


if __name__ == '__main__':
    main()
